name: 'Weekly Meeting'

on:
  schedule:
  - cron: '0 0 * * 1,3'
  
  workflow_dispatch:

jobs:
  open:
    name: Create a new issue from template
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: lowply/issue-from-template@v0.1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IFT_TEMPLATE_NAME: issue-template.md
